### PR TITLE
Resolve apply requirements bug

### PR DESCRIPTION
**Pull request by samrabelachew**
In the instance a user attempts to apply a PR when it’s not yet mergeable, future applies will fail unless the entire Atlantis process is re-run again from an initial plan.

This is because the `ProjectPlanStatus` model is tied to an assumption of the Atlantis PR cycle linearly following `plan—>policy check—>apply flow`. In the example described above, the `ProjectPlanStatus` would not be equal to `PassedPolicyCheckStatus`, even though it is mergeable/passed all policy checks because the initial apply failed. 

To solve this, rather than rely on the ProjectPlanStatus to determine policy approval, we can create a new boolean field that can answer this question. The field is set to true when an organic policy check (i.e. generated after an Atlantis plan) passes or if the approve policy command is run successfully.

### CODE REVIEW

**Review by nishkrishnan — COMMENTED** [review]
Does this still ensure that, when new "plans" are run (such as through a comment/autoplan) users will be required to get an approval even if there's been a previous approval?

**Review by nishkrishnan — COMMENTED** [review]
Did you consider an approach where we just don't persist a failed apply status for when apply requirements fail? and only persist the status when the tf operation is actually run.  

This forces you to re-run plan again after an actual tf apply failure, but also ensures you can run apply immediately again, if there's a failing apply requirement.

**Comment by samrabelachew** [comment]
> Did you consider an approach where we just don't persist a failed apply status for when apply requirements fail? and only persist the status when the tf operation is actually run.
> 
> This forces you to re-run plan again after an actual tf apply failure, but also ensures you can run apply immediately again, if there's a failing apply requirement.



> Does this still ensure that, when new "plans" are run (such as through a comment/autoplan) users will be required to get an approval even if there's been a previous approval?

Modified the condition slightly, but all new plans go through the policy check step (comment/auto) so generate new policy results: https://github.com/lyft/atlantis/pull/242/files#diff-bfcae20bf88c76b134d759aee2b2f98d89e8f63853fb1caab7571d83d6475925R67-R77

**Comment by samrabelachew** [comment]
> Did you consider an approach where we just don't persist a failed apply status for when apply requirements fail? and only persist the status when the tf operation is actually run.
> 
> This forces you to re-run plan again after an actual tf apply failure, but also ensures you can run apply immediately again, if there's a failing apply requirement.

This is also an option, but I believe may take more refactoratoring since all command runs modify this field upon any success/failure results.

**Pull request closed without merging**
