### PR TITLE
Adding logic to clear terminal screen when running new plan 

### PR DESCRIPTION
**Pull request by Aayyush**

### CODE REVIEW

**Comment by Aayyush** [comment]
When re-initializing a plan, we want to clear the terminal UI. There are two ways to do it: 
- Clear the terminal UI when "`Initializing the backend...`" msg is received (chosen approach)
- When atlantis plan is run, find the exact ws connection that needs to clear the terminal UI and send a CLEAR msg. Since we are a stateless service, I don't think it is possible to retrieve a particular ws connection. 

This approach relies on the fact that every time a plan is run, the first log msg is `Initializing the backend... ` It is very unlikely that this will be changed in the future imo.

**Comment by msarvar** [comment]
@Aayyush as discussed in our daily meeting you can use [Clear](https://github.com/lyft/atlantis/blob/49d885bde0b7d26946b30a240bd00db7d15bcfe0/server/events/project_command_runner.go#L305) function to send a custom message to the UI that will clear the logs.

**Review by msarvar — APPROVED** [review]
looks great! Let's get it merged

**Pull request merged**
